Pair Módulo 3 Lección 3

Diferencia entre una Serie y un DataFrame

Serie es unidimensional
DataFrame es bidimensional
Una serie es una columna de un dataframe


Crea un array de dos dimensiones con 4 filas y 3 columnas.

Convierte el array en un DataFrame donde las columnas se llamen "España", "Francia" e "Italia".

Descarga el archivo "medallas" y carga el DataFrame.

In [10]:
import numpy as np
import random

In [11]:
import pandas as pd

In [18]:
arr1 = np.random.randint(0,20,(4,3))

In [19]:
print(arr1)

[[13 13  6]
 [14 15  3]
 [12 10 11]
 [11 15  0]]


In [20]:
df = pd.DataFrame(arr1, columns=['España', 'Italia', 'Francia'])

In [21]:
df

España  Italia  Francia
0      13      13        6
1      14      15        3
2      12      10       11
3      11      15        0

In [22]:
df.columns

Index(['España', 'Italia', 'Francia'], dtype='object')

In [47]:
df2 = pd.read_csv("/Users/Usuario/Documents/Adalab49/Módulo 3/Lección 2_Pandas/medallas.csv",index_col=0)

In [48]:
df2.head(10)

País   Oro  Plata  Bronce
1             China  1473    994     720
2             Japón  1032   1037     985
3     Corea del Sur   745    663     827
4              Irán   179    181     197
5        Kazajistán   155    158     224
6             India   154    202     315
7         Tailandia   132    175     278
8         Indonesia   112    131     240
9      China Taipéi    99    144     276
10  Corea del Norte    91    120     235



Usando el loc extrae todas las columnas de la fila de Tailandia.

Usando el loc extrae todas las columnas de China e Irán.

Usando el loc extrae solo las columnas de "Oro", "Plata" y "Bronce" de China e Irán.

Usando el iloc extrae la información de la India. Devolved todas las columnas.



In [57]:
df2.loc[7]

País      Tailandia
Oro             132
Plata           175
Bronce          278
Name: 7, dtype: object

In [58]:
df2.iloc[7]

País      Indonesia
Oro             112
Plata           131
Bronce          240
Name: 8, dtype: object

In [62]:
df2.loc[[1,4]]


País   Oro  Plata  Bronce
1  China  1473    994     720
4   Irán   179    181     197

In [64]:
df2.loc[[1,4], "Oro":"Bronce"]

Oro  Plata  Bronce
1  1473    994     720
4   179    181     197

In [66]:
df2.loc[[1,4], "Bronce":"Oro":-1]

Bronce  Plata   Oro
1     720    994  1473
4     197    181   179

In [67]:
df2.iloc[5]

País      India
Oro         154
Plata       202
Bronce      315
Name: 6, dtype: object

Usando el iloc extrae todas las columnas de los países que estén en posición impar. La primera que nos tendría que salir es Japón y la última Corea del Norte.

Utilizando el código del ejercicio anterior, selecciona unicamente las columnas "Oro", "Plata" y "Bronce".



In [68]:
df2.head(10)

País   Oro  Plata  Bronce
1             China  1473    994     720
2             Japón  1032   1037     985
3     Corea del Sur   745    663     827
4              Irán   179    181     197
5        Kazajistán   155    158     224
6             India   154    202     315
7         Tailandia   132    175     278
8         Indonesia   112    131     240
9      China Taipéi    99    144     276
10  Corea del Norte    91    120     235

Contesta a las siguientes preguntas:

¿Qué país consiguió más de 200 medallas de oro?

¿Qué país consiguió más de 200 medallas de oro y más de 1000 de plata?

¿Qué país consiguió más de 200 medallas de oro o más de 700 de bronce?

Crea una nueva columna que se llame "total" que sea el resultado de la suma de todas las medallas obtenidas por cada país.